[project]
name = "data-science"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "mdutils>=1.8.0",
    "nbformat>=5.10.4",
    "notebook>=7.4.7",
    "numpy>=2.3.3",
]
